
DROP TABLE IF EXISTS stacks_table;

CREATE TABLE stacks_table (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  wall1 TEXT NOT NULL,
  wall2 TEXT NOT NULL,
  wall3 TEXT NOT NULL,
  wall4 TEXT NOT NULL,
  wall5 TEXT NOT NULL,
  wall6 TEXT NOT NULL
);